#%RAML 1.0
title: MusiBondi Events API Definitinon
description: Method API definition for Events manager
baseUri: http://localhost:8080/api/{version}
version: 0.1
protocols: [ HTTP, HTTPS ]
mediaType: application/json
/events:
  post:
    description: |
      Create a new event
    body:
      application/json:
        schema: {
          "userId": [{ "type": "string" }],
          "startDate": date-only,
          "endDate": date-only,
          "tags": [{ "type": "string" }],
          "playlistId": { "type": "string" },
          "type": { "type": "string" }
          }
    responses:
      200:
        description: |
          Succesfully event creation
        body:
          application/json:
            schema: {
              "eventId": { "type": "string" }
              }
      400:
        description: |
          Invalid request, is not possible create event

  /{eventId}:
  get:
    description: |
      Retrieve event by ID
    responses:
      200:
        body:
          application/json:
            schema: {
              "userId": [{ "type": "string" }],
              "startDate": date-only,
              "endDate": date-only,
              "tags": [{ "type": "string" }],
              "playlistId": { "type": "string" },
              "type": { "type": "string" }
              }
        description: |
          Succesfully retrieved the Event
      404:
        description: |
          Event not found
